mod ABP is
  sorts Bit Mensaje Canal Estado .
  ops 0 1 : -> Bit .
  ops _>> <<_ : Bit -> Mensaje .
  subsort Mensaje < Canal .
  op perdido : -> Canal .
  op A{_}_B{_} : Bit Canal Bit -> Estado .
  var M : Mensaje .
  vars X Y Z : Bit .
  rl [perdida] : A{X} M B{Y} => A{X} perdido B{Y} .
  rl [B-recibe] : A{X} Z >> B{Y} => A{X} Z >> B{Z} .
  rl [B-repite] : A{X} M B{Y} => A{X} << Y B{Y} .
  ...
endm
